extends CharacterBody3D

## Player.gd

const SPEED: float       = 5.5
const GRAVITY: float     = 9.8
const ZOOM_MIN: float    = 3.0
const ZOOM_MAX: float    = 16.0
const CAM_SMOOTH: float  = 14.0
const ZOOM_SMOOTH: float = 8.0

var _spring_arm: SpringArm3D
var _mesh: MeshInstance3D

var _target_yaw: float   = 0.0
var _target_pitch: float = deg_to_rad(-35.0)
var _target_zoom: float  = 8.0

func _ready() -> void:
	add_to_group("player")
    	_build_mesh()
        	_build_camera()
            	position = Vector3(0, 0.9, 0)

                func _build_mesh() -> void:
                	# Collision
                    	var col := CollisionShape3D.new()
                        	var caps := CapsuleShape3D.new()
                            	caps.radius = 0.4
                                	caps.height = 1.8 # Auf Standardmaß korrigiert
                                    	col.shape = caps
                                        	col.position.y = 0.9
                                            	add_child(col)

                                                	# Visual Mesh
                                                    	_mesh = MeshInstance3D.new()
                                                        	var cm := CapsuleMesh.new()
                                                            	cm.radius = 0.4
                                                                	cm.height = 1.8
                                                                    	_mesh.mesh = cm
                                                                        	
                                                                            	var mat := StandardMaterial3D.new()
                                                                                	mat.albedo_color = Color(0.95, 0.6, 0.05)
                                                                                    	_mesh.material_override = mat
                                                                                        	_mesh.position.y = 0.9
                                                                                            	add_child(_mesh)

                                                                                                func _build_camera() -> void:
                                                                                                	_spring_arm = SpringArm3D.new()
                                                                                                    	_spring_arm.spring_length = _target_zoom
                                                                                                        	_spring_arm.position = Vector3(0, 1.5, 0)
                                                                                                            	_spring_arm.rotation.x = _target_pitch
                                                                                                                	# Wichtig: Der SpringArm sollte nicht mit dem Mesh rotieren
                                                                                                                    	_spring_arm.top_level = false 
                                                                                                                        	add_child(_spring_arm)

                                                                                                                            	var cam := Camera3D.new()
                                                                                                                                	cam.current = true
                                                                                                                                    	_spring_arm.add_child(cam)

                                                                                                                                        func _physics_process(delta: float) -> void:
                                                                                                                                        	var touch := _get_touch()
                                                                                                                                            	if not touch:
                                                                                                                                                		return
                                                                                                                                                        		
                                                                                                                                                                	_handle_movement(touch, delta)
                                                                                                                                                                    	_handle_camera(touch, delta)

                                                                                                                                                                        func _handle_movement(touch: Node, delta: float) -> void:
                                                                                                                                                                        	var input_vec: Vector2 = touch.get("js_vec") if touch else Vector2.ZERO

                                                                                                                                                                            	# Kamera-Relativität prüfen (Settings-Check)
                                                                                                                                                                                	var cam_relative: bool = true
                                                                                                                                                                                    	var raw: Variant = _get_setting("cam_relative")
                                                                                                                                                                                        	if raw != null:
                                                                                                                                                                                            		cam_relative = bool(raw)

                                                                                                                                                                                                    	if input_vec.length() > 0.05:
                                                                                                                                                                                                        		var dir := Vector3.ZERO
                                                                                                                                                                                                                		if cam_relative:
                                                                                                                                                                                                                        			# Richtung basierend auf Kamera-Y-Rotation berechnen
                                                                                                                                                                                                                                    			var cam_basis := _spring_arm.global_transform.basis
                                                                                                                                                                                                                                                			var fwd := Vector3(cam_basis.z.x, 0, cam_basis.z.z).normalized() # Z ist in Godot "Rückwärts"
                                                                                                                                                                                                                                                            			var right := Vector3(cam_basis.x.x, 0, cam_basis.x.z).normalized()
                                                                                                                                                                                                                                                                        			# Da input_vec.y bei Joysticks oft nach oben negativ ist:
                                                                                                                                                                                                                                                                                    			dir = (fwd * -input_vec.y + right * input_vec.x).normalized()
                                                                                                                                                                                                                                                                                                		else:
                                                                                                                                                                                                                                                                                                        			dir = Vector3(input_vec.x, 0, -input_vec.y).normalized()

                                                                                                                                                                                                                                                                                                                    		velocity.x = dir.x * SPEED
                                                                                                                                                                                                                                                                                                                            		velocity.z = dir.z * SPEED

                                                                                                                                                                                                                                                                                                                                    		# Mesh in Laufrichtung drehen
                                                                                                                                                                                                                                                                                                                                            		var target_angle := atan2(dir.x, dir.z)
                                                                                                                                                                                                                                                                                                                                                    		_mesh.rotation.y = lerp_angle(_mesh.rotation.y, target_angle, 12.0 * delta)
                                                                                                                                                                                                                                                                                                                                                            	else:
                                                                                                                                                                                                                                                                                                                                                                		velocity.x = move_toward(velocity.x, 0, SPEED * 8 * delta)
                                                                                                                                                                                                                                                                                                                                                                        		velocity.z = move_toward(velocity.z, 0, SPEED * 8 * delta)

                                                                                                                                                                                                                                                                                                                                                                                	# Gravitation
                                                                                                                                                                                                                                                                                                                                                                                    	if not is_on_floor():
                                                                                                                                                                                                                                                                                                                                                                                        		velocity.y -= GRAVITY * delta
                                                                                                                                                                                                                                                                                                                                                                                                	else:
                                                                                                                                                                                                                                                                                                                                                                                                    		velocity.y = 0.0

                                                                                                                                                                                                                                                                                                                                                                                                            	move_and_slide()

                                                                                                                                                                                                                                                                                                                                                                                                                func _handle_camera(touch: Node, delta: float) -> void:
                                                                                                                                                                                                                                                                                                                                                                                                                	# Rotation (Yaw & Pitch)
                                                                                                                                                                                                                                                                                                                                                                                                                    	if touch.get("cam_delta") != Vector2.ZERO:
                                                                                                                                                                                                                                                                                                                                                                                                                        		var c_delta: Vector2 = touch.get("cam_delta")
                                                                                                                                                                                                                                                                                                                                                                                                                                		_target_yaw -= c_delta.x * 0.007
                                                                                                                                                                                                                                                                                                                                                                                                                                        		_target_pitch = clamp(_target_pitch - c_delta.y * 0.007, deg_to_rad(-65), deg_to_rad(-10))
                                                                                                                                                                                                                                                                                                                                                                                                                                                		touch.set("cam_delta", Vector2.ZERO)

                                                                                                                                                                                                                                                                                                                                                                                                                                                        	# Zoom
                                                                                                                                                                                                                                                                                                                                                                                                                                                            	if touch.get("zoom_delta") != 0.0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                		var z_delta: float = touch.get("zoom_delta")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		_target_zoom = clamp(_target_zoom + z_delta, ZOOM_MIN, ZOOM_MAX)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		touch.set("zoom_delta", 0.0)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	# Glättung anwenden
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	_spring_arm.rotation.y = lerp_angle(_spring_arm.rotation.y, _target_yaw, CAM_SMOOTH * delta)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	_spring_arm.rotation.x = lerp(_spring_arm.rotation.x, _target_pitch, CAM_SMOOTH * delta)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	_spring_arm.spring_length = lerp(_spring_arm.spring_length, _target_zoom, ZOOM_SMOOTH * delta)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # --- Hilfsfunktionen für die Kommunikation ---

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        func _get_touch() -> Node:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	# Sucht den TouchInput-Node im SceneTree
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	return get_parent().get_node_or_null("TouchInput")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                func _get_setting(key: String) -> Variant:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	# Hier müsstest du deine Settings-Logik abfragen
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	# Da Main.gd die Settings hält, wäre ein Zugriff dort sinnvoll
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	var settings = get_parent().get_node_or_null("Settings")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	if settings and settings.has_method("get_val"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		return settings.get_val(key)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	return null