extends CanvasLayer
## Settings.gd — Einstellungs-Panel

signal ui_offset_changed(offset: Vector2)

var _panel: ColorRect
var _values: Dictionary = {
    	"cam_relative":    true,
        	"fixed_joystick":  true,
            	"screen_rotation": 0,
                	"cam_smooth":      14.0,
                    	"zoom_smooth":     8.0,
                        	"ui_offset_x":     0.0,
                            	"ui_offset_y":     0.0,
}

const ROTATION_LABELS: Array = [
    	"Frei (Sensor)",
        	"Nur Hochkant",
            	"Nur Querformat",
                	"Hochkant (Umg.)",
]
const ROTATION_MODES: Array = [
    	DisplayServer.SCREEN_SENSOR,
        	DisplayServer.SCREEN_PORTRAIT,
            	DisplayServer.SCREEN_LANDSCAPE,
                	DisplayServer.SCREEN_SENSOR_PORTRAIT,
]

func _ready() -> void:
	add_to_group("settings")
    	var vp := get_viewport().get_visible_rect().size
        	_build_panel(vp)
            	_panel.visible = false
                	get_viewport().size_changed.connect(_on_viewport_resized)

                    func _on_viewport_resized() -> void:
                    	if not _panel: return
                        	var vp := get_viewport().get_visible_rect().size
                            	# Panel zentrieren und Größe anpassen
                                	_panel.size = Vector2(min(680, vp.x * 0.9), vp.y * 0.85)
                                    	_panel.position = (vp * 0.5) - (_panel.size * 0.5)

                                        func toggle() -> void:
                                        	_panel.visible = not _panel.visible
                                            	if _panel.visible:
                                                		# Sicherstellen, dass es beim Öffnen richtig positioniert ist
                                                        		_on_viewport_resized()

                                                                func is_open() -> bool: # Wichtig für TouchInput.gd
                                                                	return _panel != null and _panel.visible

                                                                    func get_val(key: String) -> Variant: # Wichtig für Player.gd
                                                                    	return _values.get(key, null)

                                                                        func _build_panel(vp: Vector2) -> void:
                                                                        	_panel = ColorRect.new()
                                                                            	_panel.color = Color(0.08, 0.08, 0.08, 0.95)
                                                                                	_panel.size = Vector2(680, vp.y * 0.85)
                                                                                    	_panel.position = (vp * 0.5) - (_panel.size * 0.5)
                                                                                        	add_child(_panel)

                                                                                            	# Titel
                                                                                                	var title := Label.new()
                                                                                                    	title.text = "Settings"
                                                                                                        	title.position = Vector2(20, 16)
                                                                                                            	title.add_theme_font_size_override("font_size", 34)
                                                                                                                	_panel.add_child(title)

                                                                                                                    	var hline := ColorRect.new()
                                                                                                                        	hline.color = Color(1, 1, 1, 0.15)
                                                                                                                            	hline.size = Vector2(_panel.size.x - 40, 2)
                                                                                                                                	hline.position = Vector2(20, 64)
                                                                                                                                    	_panel.add_child(hline)

                                                                                                                                        	# Scroll Container
                                                                                                                                            	var scroll := ScrollContainer.new()
                                                                                                                                                	scroll.position = Vector2(0, 72)
                                                                                                                                                    	scroll.size = Vector2(_panel.size.x, _panel.size.y - 72)
                                                                                                                                                        	scroll.horizontal_scroll_mode = ScrollContainer.SCROLL_MODE_DISABLED
                                                                                                                                                            	_panel.add_child(scroll)

                                                                                                                                                                	var content := VBoxContainer.new()
                                                                                                                                                                    	content.size_flags_horizontal = Control.SIZE_EXPAND_FILL
                                                                                                                                                                        	scroll.add_child(content)

                                                                                                                                                                            	# --- SEKTIONEN ---
                                                                                                                                                                                	_section(content, "Steuerung", "Joystick- und Bewegungs-Optionen")
                                                                                                                                                                                    	content.add_child(_make_toggle("fixed_joystick", "Fixer Joystick"))
                                                                                                                                                                                        	content.add_child(_make_toggle("cam_relative", "Kamera-Relativ"))
                                                                                                                                                                                            	
                                                                                                                                                                                                	_hline(content)
                                                                                                                                                                                                    	_section(content, "Display", "Bildschirm-Einstellungen")
                                                                                                                                                                                                        	content.add_child(_make_rotation_picker())
                                                                                                                                                                                                            	
                                                                                                                                                                                                                	_hline(content)
                                                                                                                                                                                                                    	_section(content, "Kamera", "Empfindlichkeit & Glättung")
                                                                                                                                                                                                                        	content.add_child(_make_slider("cam_smooth", 2.0, 30.0, 1.0, "Rotation"))
                                                                                                                                                                                                                            	content.add_child(_make_slider("zoom_smooth", 1.0, 20.0, 1.0, "Zoom"))
                                                                                                                                                                                                                                	
                                                                                                                                                                                                                                    	_hline(content)
                                                                                                                                                                                                                                        	_section(content, "Interface", "UI-Position anpassen")
                                                                                                                                                                                                                                            	content.add_child(_make_slider("ui_offset_x", -200.0, 200.0, 5.0, "Horizontal", _on_ui_offset_changed))
                                                                                                                                                                                                                                                	content.add_child(_make_slider("ui_offset_y", -200.0, 200.0, 5.0, "Vertikal", _on_ui_offset_changed))

                                                                                                                                                                                                                                                    	# Schließen Button
                                                                                                                                                                                                                                                        	_spacer(content, 20)
                                                                                                                                                                                                                                                            	var close := Button.new()
                                                                                                                                                                                                                                                                	close.text = "X Schließen"
                                                                                                                                                                                                                                                                    	close.custom_minimum_size = Vector2(280, 60)
                                                                                                                                                                                                                                                                        	close.pressed.connect(toggle)
                                                                                                                                                                                                                                                                            	var center := CenterContainer.new()
                                                                                                                                                                                                                                                                                	center.add_child(close)
                                                                                                                                                                                                                                                                                    	content.add_child(center)
                                                                                                                                                                                                                                                                                        	_spacer(content, 30)

                                                                                                                                                                                                                                                                                            # --- UI GENERATOREN ---

                                                                                                                                                                                                                                                                                            func _make_toggle(key: String, label_text: String) -> Control:
                                                                                                                                                                                                                                                                                            	var hbox := HBoxContainer.new()
                                                                                                                                                                                                                                                                                                	hbox.add_theme_constant_override("separation", 20)
                                                                                                                                                                                                                                                                                                    	
                                                                                                                                                                                                                                                                                                        	var lbl := Label.new()
                                                                                                                                                                                                                                                                                                            	lbl.text = label_text
                                                                                                                                                                                                                                                                                                                	lbl.custom_minimum_size = Vector2(250, 0)
                                                                                                                                                                                                                                                                                                                    	hbox.add_child(lbl)
                                                                                                                                                                                                                                                                                                                        	
                                                                                                                                                                                                                                                                                                                            	var btn := Button.new()
                                                                                                                                                                                                                                                                                                                                	btn.text = "EIN" if _values[key] else "AUS"
                                                                                                                                                                                                                                                                                                                                    	btn.custom_minimum_size = Vector2(120, 50)
                                                                                                                                                                                                                                                                                                                                        	btn.pressed.connect(func():
                                                                                                                                                                                                                                                                                                                                            		_values[key] = not _values[key]
                                                                                                                                                                                                                                                                                                                                                    		btn.text = "EIN" if _values[key] else "AUS"
                                                                                                                                                                                                                                                                                                                                                            	)
                                                                                                                                                                                                                                                                                                                                                                	hbox.add_child(btn)
                                                                                                                                                                                                                                                                                                                                                                    	
                                                                                                                                                                                                                                                                                                                                                                        	var margin := MarginContainer.new()
                                                                                                                                                                                                                                                                                                                                                                            	margin.add_theme_constant_override("margin_left", 25)
                                                                                                                                                                                                                                                                                                                                                                                	margin.add_child(hbox)
                                                                                                                                                                                                                                                                                                                                                                                    	return margin

                                                                                                                                                                                                                                                                                                                                                                                        func _make_slider(key: String, mn: float, mx: float, step: float, label_text: String, callback: Callable = Callable()) -> Control:
                                                                                                                                                                                                                                                                                                                                                                                        	var vbox := VBoxContainer.new()
                                                                                                                                                                                                                                                                                                                                                                                            	var lbl := Label.new()
                                                                                                                                                                                                                                                                                                                                                                                                	lbl.text = label_text + ": " + str(_values[key])
                                                                                                                                                                                                                                                                                                                                                                                                    	vbox.add_child(lbl)
                                                                                                                                                                                                                                                                                                                                                                                                        	
                                                                                                                                                                                                                                                                                                                                                                                                            	var slider := HSlider.new()
                                                                                                                                                                                                                                                                                                                                                                                                                	slider.min_value = mn
                                                                                                                                                                                                                                                                                                                                                                                                                    	slider.max_value = mx
                                                                                                                                                                                                                                                                                                                                                                                                                        	slider.step = step
                                                                                                                                                                                                                                                                                                                                                                                                                            	slider.value = _values[key]
                                                                                                                                                                                                                                                                                                                                                                                                                                	slider.custom_minimum_size = Vector2(400, 40)
                                                                                                                                                                                                                                                                                                                                                                                                                                    	slider.value_changed.connect(func(v):
                                                                                                                                                                                                                                                                                                                                                                                                                                        		_values[key] = v
                                                                                                                                                                                                                                                                                                                                                                                                                                                		lbl.text = label_text + ": " + str(v)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        		if callback.is_valid(): callback.call()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                	)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	vbox.add_child(slider)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	var margin := MarginContainer.new()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	margin.add_theme_constant_override("margin_left", 25)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	margin.add_theme_constant_override("margin_bottom", 10)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	margin.add_child(vbox)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	return margin

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                func _make_rotation_picker() -> Control:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	var vbox := VBoxContainer.new()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	vbox.add_theme_constant_override("separation", 5)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	for i in ROTATION_LABELS.size():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		var btn := Button.new()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		btn.text = ROTATION_LABELS[i]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		btn.alignment = HORIZONTAL_ALIGNMENT_LEFT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		btn.pressed.connect(func():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			DisplayServer.screen_set_orientation(ROTATION_MODES[i])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			_values["screen_rotation"] = i
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		vbox.add_child(btn)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	var margin := MarginContainer.new()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	margin.add_theme_constant_override("margin_left", 25)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	margin.add_child(vbox)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	return margin

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # --- HELPERS ---

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        func _on_ui_offset_changed() -> void:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	ui_offset_changed.emit(Vector2(_values["ui_offset_x"], _values["ui_offset_y"]))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            func _section(parent: Control, title: String, sub: String) -> void:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	var l1 := Label.new(); l1.text = title; l1.add_theme_font_size_override("font_size", 24)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	var l2 := Label.new(); l2.text = sub; l2.add_theme_color_override("font_color", Color.GRAY)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	var m := MarginContainer.new()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	m.add_theme_constant_override("margin_left", 20)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	var v := VBoxContainer.new()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	v.add_child(l1); v.add_child(l2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	m.add_child(v)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	parent.add_child(m)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	_spacer(parent, 10)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                func _hline(parent: Control) -> void:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	_spacer(parent, 10)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	var line := ColorRect.new()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	line.color = Color(1,1,1,0.1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	line.custom_minimum_size = Vector2(0, 2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	parent.add_child(line)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	_spacer(parent, 15)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        func _spacer(parent: Control, h: int) -> void:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	var s := Control.new(); s.custom_minimum_size.y = h
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	parent.add_child(s)extends
]
]
}