extends Node
## TouchInput.gd

var js_vec: Vector2    = Vector2.ZERO
var cam_delta: Vector2 = Vector2.ZERO
var zoom_delta: float  = 0.0

var _js_finger: int     = -1
var _js_origin: Vector2 = Vector2.ZERO
const JS_RADIUS: float  = 90.0

var _right_fingers: Dictionary = {}
var _pinch_last_dist: float    = 0.0
var _cam_last: Vector2         = Vector2.ZERO
var _cam_finger: int           = -1

var _js_base: ColorRect = null
var _js_knob: ColorRect = null


func _ready() -> void:
	add_to_group("touch_input")


    func register_joystick_visuals(base: ColorRect, knob: ColorRect) -> void:
    	_js_base = base
        	_js_knob = knob


            func _is_settings_open() -> bool:
            	var nodes: Array = get_tree().get_nodes_in_group("settings")
                	if nodes.size() > 0 and nodes[0].has_method("is_settings_open"):
                    		return nodes[0].is_settings_open()
                            	return false


                                func _input(event: InputEvent) -> void:
                                	if _is_settings_open():
                                    		js_vec     = Vector2.ZERO
                                            		cam_delta  = Vector2.ZERO
                                                    		zoom_delta = 0.0
                                                            		return

                                                                    	var sw: float = get_viewport().get_visible_rect().size.x

                                                                        	if event is InputEventScreenTouch:
                                                                            		_handle_touch(event, sw)
                                                                                    	elif event is InputEventScreenDrag:
                                                                                        		_handle_drag(event, sw)
                                                                                                	elif event is InputEventMouseMotion:
                                                                                                    		if Input.is_mouse_button_pressed(MOUSE_BUTTON_RIGHT):
                                                                                                            			cam_delta += event.relative
                                                                                                                        	elif event is InputEventMouseButton and event.pressed:
                                                                                                                            		if event.button_index == MOUSE_BUTTON_WHEEL_UP:
                                                                                                                                    			zoom_delta -= 0.5
                                                                                                                                                		elif event.button_index == MOUSE_BUTTON_WHEEL_DOWN:
                                                                                                                                                        			zoom_delta += 0.5


                                                                                                                                                                    func _handle_touch(event: InputEventScreenTouch, sw: float) -> void:
                                                                                                                                                                    	var pos: Vector2 = event.position
                                                                                                                                                                        	var is_left: bool = pos.x < sw * 0.5

                                                                                                                                                                            	if event.pressed:
                                                                                                                                                                                		if is_left:
                                                                                                                                                                                        			if _js_finger < 0:
                                                                                                                                                                                                    				_js_finger = event.index
                                                                                                                                                                                                                    				_js_origin = pos
                                                                                                                                                                                                                                    				_update_js_visuals(pos, Vector2.ZERO)
                                                                                                                                                                                                                                                    		else:
                                                                                                                                                                                                                                                            			_right_fingers[event.index] = pos
                                                                                                                                                                                                                                                                        			if _right_fingers.size() == 1:
                                                                                                                                                                                                                                                                                    				_cam_finger = event.index
                                                                                                                                                                                                                                                                                                    				_cam_last   = pos
                                                                                                                                                                                                                                                                                                                    			elif _right_fingers.size() == 2:
                                                                                                                                                                                                                                                                                                                                				_cam_finger = -1
                                                                                                                                                                                                                                                                                                                                                				var keys: Array = _right_fingers.keys()
                                                                                                                                                                                                                                                                                                                                                                				_pinch_last_dist = (_right_fingers[keys[0]] as Vector2).distance_to(
                                                                                                                                                                                                                                                                                                                                                                                    					_right_fingers[keys[1]] as Vector2
                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                	else:
                                                                                                                                                                                                                                                                                                                                                                                    		if event.index == _js_finger:
                                                                                                                                                                                                                                                                                                                                                                                            			_js_finger = -1
                                                                                                                                                                                                                                                                                                                                                                                                        			js_vec     = Vector2.ZERO
                                                                                                                                                                                                                                                                                                                                                                                                                    			_reset_js_visuals()
                                                                                                                                                                                                                                                                                                                                                                                                                                		if event.index in _right_fingers:
                                                                                                                                                                                                                                                                                                                                                                                                                                        			_right_fingers.erase(event.index)
                                                                                                                                                                                                                                                                                                                                                                                                                                                    			_pinch_last_dist = 0.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                			if _right_fingers.size() == 1:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            				_cam_finger = _right_fingers.keys()[0]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            				_cam_last   = _right_fingers[_cam_finger]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			elif _right_fingers.size() == 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        				_cam_finger = -1


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        func _handle_drag(event: InputEventScreenDrag, sw: float) -> void:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	var is_left: bool = event.index == _js_finger

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	if is_left:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		var delta: Vector2   = event.position - _js_origin
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		var clamped: Vector2 = delta.limit_length(JS_RADIUS)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		js_vec = clamped / JS_RADIUS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		_update_js_visuals(_js_origin, clamped)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		return

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	if event.index in _right_fingers:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		_right_fingers[event.index] = event.position

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	if _right_fingers.size() == 2:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		var keys: Array = _right_fingers.keys()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		var new_dist: float = (_right_fingers[keys[0]] as Vector2).distance_to(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			_right_fingers[keys[1]] as Vector2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		if _pinch_last_dist > 0.0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			zoom_delta += (_pinch_last_dist - new_dist) * 0.025
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		_pinch_last_dist = new_dist
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	elif event.index == _cam_finger:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		var d: Vector2 = event.position - _cam_last
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		_cam_last      = event.position
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		cam_delta     += d


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                func _update_js_visuals(origin: Vector2, offset: Vector2) -> void:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	if _js_base:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		_js_base.position = origin - Vector2(JS_RADIUS, JS_RADIUS)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	if _js_knob:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		_js_knob.position = origin + offset - Vector2(30, 30)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        func _reset_js_visuals() -> void:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	if _js_base and _js_knob:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		_js_knob.position = _js_base.position + Vector2(JS_RADIUS - 30, JS_RADIUS - 30)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                )