extends Node

## TouchInput.gd

var js_vec: Vector2    = Vector2.ZERO
var cam_delta: Vector2 = Vector2.ZERO
var zoom_delta: float  = 0.0

var _js_finger: int     = -1
var _js_origin: Vector2 = Vector2.ZERO
const JS_RADIUS: float  = 90.0

var _right_fingers: Dictionary = {}
var _pinch_last_dist: float    = 0.0
var _cam_last: Vector2         = Vector2.ZERO
var _cam_finger: int           = -1

var _js_base: Control = null
var _js_knob: Control = null

func _ready() -> void:
	add_to_group("touch_input")

    func register_joystick_visuals(base: Control, knob: Control) -> void:
    	_js_base = base
        	_js_knob = knob
            	_reset_js_visuals()

                func _is_settings_open() -> bool:
                	# Prüft, ob das Einstellungsmenü gerade aktiv ist
                    	var nodes := get_tree().get_nodes_in_group("settings")
                        	if nodes.size() > 0:
                            		var s = nodes[0]
                                    		if s.has_method("is_open"): return s.is_open()
                                            		if "visible" in s: return s.visible
                                                    	return false

                                                        func _input(event: InputEvent) -> void:
                                                        	if _is_settings_open():
                                                            		js_vec = Vector2.ZERO
                                                                    		cam_delta = Vector2.ZERO
                                                                            		zoom_delta = 0.0
                                                                                    		return

                                                                                            	var sw: float = get_viewport().get_visible_rect().size.x

                                                                                                	# 1. Touch & Drag (Mobile)
                                                                                                    	if event is InputEventScreenTouch:
                                                                                                        		_handle_touch(event, sw)
                                                                                                                	elif event is InputEventScreenDrag:
                                                                                                                    		_handle_drag(event, sw)
                                                                                                                            	
                                                                                                                                	# 2. Mouse Support (PC Testing)
                                                                                                                                    	elif event is InputEventMouseMotion:
                                                                                                                                        		if Input.is_mouse_button_pressed(MOUSE_BUTTON_RIGHT):
                                                                                                                                                			cam_delta += event.relative
                                                                                                                                                            	elif event is InputEventMouseButton and event.pressed:
                                                                                                                                                                		if event.button_index == MOUSE_BUTTON_WHEEL_UP:
                                                                                                                                                                        			zoom_delta -= 0.5
                                                                                                                                                                                    		elif event.button_index == MOUSE_BUTTON_WHEEL_DOWN:
                                                                                                                                                                                            			zoom_delta += 0.5

                                                                                                                                                                                                        func _handle_touch(event: InputEventScreenTouch, sw: float) -> void:
                                                                                                                                                                                                        	var pos: Vector2 = event.position
                                                                                                                                                                                                            	var is_left: bool = pos.x < sw * 0.5

                                                                                                                                                                                                                	if event.pressed:
                                                                                                                                                                                                                    		if is_left and _js_finger < 0:
                                                                                                                                                                                                                            			_js_finger = event.index
                                                                                                                                                                                                                                        			_js_origin = pos
                                                                                                                                                                                                                                                    			_update_js_visuals(pos, Vector2.ZERO)
                                                                                                                                                                                                                                                                		else:
                                                                                                                                                                                                                                                                        			_right_fingers[event.index] = pos
                                                                                                                                                                                                                                                                                    			if _right_fingers.size() == 1:
                                                                                                                                                                                                                                                                                                				_cam_finger = event.index
                                                                                                                                                                                                                                                                                                                				_cam_last = pos
                                                                                                                                                                                                                                                                                                                                			elif _right_fingers.size() == 2:
                                                                                                                                                                                                                                                                                                                                            				_cam_finger = -1
                                                                                                                                                                                                                                                                                                                                                            				var keys = _right_fingers.keys()
                                                                                                                                                                                                                                                                                                                                                                            				_pinch_last_dist = _right_fingers[keys[0]].distance_to(_right_fingers[keys[1]])
                                                                                                                                                                                                                                                                                                                                                                                            	else:
                                                                                                                                                                                                                                                                                                                                                                                                		# Losgelassen
                                                                                                                                                                                                                                                                                                                                                                                                        		if event.index == _js_finger:
                                                                                                                                                                                                                                                                                                                                                                                                                			_js_finger = -1
                                                                                                                                                                                                                                                                                                                                                                                                                            			js_vec = Vector2.ZERO
                                                                                                                                                                                                                                                                                                                                                                                                                                        			_reset_js_visuals()
                                                                                                                                                                                                                                                                                                                                                                                                                                                    		
                                                                                                                                                                                                                                                                                                                                                                                                                                                            		if event.index in _right_fingers:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			_right_fingers.erase(event.index)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			_pinch_last_dist = 0.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			if _right_fingers.size() == 1:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        				_cam_finger = _right_fingers.keys()[0]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        				_cam_last = _right_fingers[_cam_finger]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    				_cam_finger = -1

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    func _handle_drag(event: InputEventScreenDrag, sw: float) -> void:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	# Joystick Drag (Links)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	if event.index == _js_finger:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		var diff: Vector2 = event.position - _js_origin
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		var clamped: Vector2 = diff.limit_length(JS_RADIUS)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		js_vec = clamped / JS_RADIUS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		_update_js_visuals(_js_origin, clamped)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		return

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	# Kamera / Zoom Drag (Rechts)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	if event.index in _right_fingers:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		_right_fingers[event.index] = event.position
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		if _right_fingers.size() == 1 and event.index == _cam_finger:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			cam_delta += (event.position - _cam_last)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			_cam_last = event.position
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		elif _right_fingers.size() == 2:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            			var keys = _right_fingers.keys()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			var dist: float = _right_fingers[keys[0]].distance_to(_right_fingers[keys[1]])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			if _pinch_last_dist > 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                				zoom_delta += (_pinch_last_dist - dist) * 0.05
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			_pinch_last_dist = dist

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # --- Visuals ---

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            func _update_js_visuals(origin: Vector2, offset: Vector2) -> void:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	if _js_base and _js_knob:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		_js_base.visible = true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		_js_base.global_position = origin - (_js_base.size * 0.5)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                		_js_knob.position = (_js_base.size * 0.5) - (_js_knob.size * 0.5) + offset

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        func _reset_js_visuals() -> void:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	if _js_base:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		_js_base.visible = falseextends